# @BeChinhPhucToan_BE_HostAddress = http://localhost:5016

# GET {{BeChinhPhucToan_BE_HostAddress}}/weatherforecast/
# Accept: application/json

###
@BeChinhPhucToan_BE_HostAddress = https://bechinhphuctoan.onrender.com

GET {{BeChinhPhucToan_BE_HostAddress}}/weatherforecast/
Accept: application/json
